name = "KEGGAPI"
uuid = "e8256861-d17c-4800-bf17-838497555b93"
authors = ["Nicholas Geoffrion", "Maria Victoria Aguilar Pontes"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
